a= float(input("valor de a: "))
b= float(input("valor de b: "))
suma = (a + b)
resta = (a - b)
division = (a / b)
producto = (a * b)
exponenciaxion = (a ** b)
modulo = (a%b)

print ("la suma es: " + str(suma))
print ("la resta es: " + str(resta))
print ("la division es: " + str(division))
print ("el producto es: " + str(producto))
print ("la exponenciaxion es: " + str(exponenciaxion))
print ("el modulo es: " + str(modulo))